### ISSUE TITLE
qpycore_chimera.cpp: has no member named 'qt4_flags'

### ISSUE THREAD

**Issue by DengkeDu** [Geontech/meta-redhawk-sdr#1]
When I run the following:
`bitbake python-pyqt`
It thrown the following:

> qpycore_chimera.cpp: In member function 'void Chimera::set_flag()':
qpycore_chimera.cpp:552:50: error: 'pyqt4ClassTypeDef {aka struct _pyqt4ClassTypeDef}' has no member named 'qt4_flags'
         _is_flag = ((pyqt4ClassTypeDef *)_type)->qt4_flags & 0x01;
                                                  ^
make[2]: *** [qpycore_chimera.o] Error 1
make[2]: Leaving directory `/buildarea/raid0/ddu/poky-krogoth-15.0.0/build-beaglebone2/tmp/work/cortexa8hf-neon-poky-linux-gnueabi/python-pyqt/4.9.6-r1/PyQt-x11-gpl-4.9.6/qpy/QtCore'
make[1]: *** [sub-QtCore-make_default] Error 2
make[1]: Leaving directory `/buildarea/raid0/ddu/poky-krogoth-15.0.0/build-beaglebone2/tmp/work/cortexa8hf-neon-poky-linux-gnueabi/python-pyqt/4.9.6-r1/PyQt-x11-gpl-4.9.6/qpy'
make: *** [sub-qpy-make_default] Error 2

**Comment by btgoodwin** [comment]
This recipe has been superseded by a more recent one in the OpenEmbedded listing and will be removed in our next update.  Have you tried using the one from the meta-oe layer?
