### ISSUE TITLE
Errror while running build-images.sh

### ISSUE THREAD

**Issue by VNDJ** [Geontech/meta-redhawk-sdr#15]
i am running the command in the build directory
`bash ../meta-redhawk-sdr/contrib/scripts/build-image.sh`
and i got the error:
`MACHINE: ettus-e3xx-sg1
BUILD_IMAGE: redhawk-usrp-uhd-image
Meta-REDHAWK-SDR Root found: ../meta-redhawk-sdr
STEP 1 - Starting Bit Bake
Loading cache: 100% |###########################################| ETA:  00:00:00
Loaded 2281 entries from dependency cache.
Parsing recipes: 100% |#########################################| Time: 00:00:00
Parsing of 1772 .bb files complete (1771 cached, 1 parsed). 2281 targets, 108 skipped, 0 masked, 0 errors.
WARNING: No bb files matched BBFILE_PATTERN_ettus-e100 '^/home/ekko/worspace/REDHAWK/oe-core/../meta-ettus/e100-bsp/'
NOTE: Resolving any missing task queue dependencies
NOTE: multiple providers are available for runtime u-boot-xlnx-dev (u-boot-xlnx-dev, u-boot-xlnx)
NOTE: consider defining a PREFERRED_PROVIDER entry to match u-boot-xlnx-dev
NOTE: multiple providers are available for jpeg (jpeg, libjpeg-turbo)
NOTE: consider defining a PREFERRED_PROVIDER entry to match jpeg
ERROR: Nothing PROVIDES 'xerces-c-native' (but virtual:native:/home/ekko/worspace/REDHAWK/oe-core/../meta-redhawk-sdr/recipes-deps/xsd/xsd_4.0.0.bb DEPENDS on or otherwise requires it). Close matches:
  re2c-native
  xrefresh-native
  xsd-native
NOTE: Runtime target 'usrp-uhd' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['usrp-uhd', 'bulkiointerfaces', 'redhawk', 'xsd-native', 'xerces-c-native']
ERROR: Required build target 'redhawk-usrp-uhd-image' has no buildable providers.
Missing or unbuildable dependency chain was: ['redhawk-usrp-uhd-image', 'usrp-uhd', 'bulkiointerfaces', 'redhawk', 'xsd-native', 'xerces-c-native']

`
i am a newer with yocto, how to fix this bb file,thank you

**Comment by rodrigo455** [comment]
I believe the pyro and krogoth branch of meta-redhawk-sdr, which is related
to the yocto releases, is currently not compatible with meta-ettus layer.
Try to use a older release of meta-redhawk-sdr.
