### ISSUE TITLE
Required processor_name value in GPP.prf.xml file

### ISSUE THREAD

**Issue by rodrigo455** [Geontech/meta-redhawk-sdr#20]
I came up with this trying to  launch a waveform for distributed systems targeting arm and x86. 
GPP.prf.xml currentlly shows:
```
  <simple id="DCE:fefb9c66-d14a-438d-ad59-2cfd1adb272b" mode="readonly" name="processor_name" type="string">
    <description>SCA required property describing the CPU type</description>
    <kind kindtype="property"/>
    <kind kindtype="configure"/>
    <kind kindtype="allocation"/>
    <action type="eq"/>
  </simple>
```
there... should have a tag `<value>armv7l</value>` . I don't know if gpp_setup script should deal with this. Maybe the other properties need the same attention

**Comment by btgoodwin** [comment]
That surprises me we would need to patch this one too.  That property is populated by the GPP on init using `sys/utsname.h`.  If you view the property while the GPP is running, what's its value?

[Line reference from core-framework/GPP/cpp](https://github.com/RedhawkSDR/core-framework/blob/develop-2.0/GPP/cpp/GPP.cpp#L430)

**Comment by btgoodwin** [comment]
Actually...no that doesn't surprise me given what we just observed with trying to patch `armv7l` all over the place because of what you pointed out in the Xilinx kernel source vs. uname.  It looks like we'll need to patch that in the GPP too (to hard-code the value in `_init()`).

**Comment by rodrigo455** [comment]
I made some manual modification, and started to run the waveform. I get this warn message repeatedly from GPP:
`2017-08-24 13:34:28 WARN  GPP_i:600 - get_component_monitor: Could not find /proc/12188/stat. The process corresponding to component component_1:waveform_236_105435713_1 is no longer there`

**Comment by btgoodwin** [comment]
This is over a year old now but I just wanted to update you that I have a patch in the works to go along with a bump to 2.2.1 that was released December 6.
