### ISSUE TITLE
omniorb switch source from http to https

### ISSUE THREAD

**Issue by chris-jo** [Geontech/meta-redhawk-sdr#4]
I tried to bake the recipe for omniorb_4.2.0.bb
It wasn't possible to fetch the source because it was forbidden.
In a bbapend file I switched the sources to https and now it works.
`SRC_URI = "https://downloads.sourceforge.net/omniorb/omniORB-4.2.0.tar.bz2;name=omniORB420tarbz2"
SRC_URI_virtclass-native = "https://downloads.sourceforge.net/omniorb/omniORB-4.2.0.tar.bz2;name=omniORB420tarbz2"`

**Comment by btgoodwin** [comment]
It looks like they moved it in the last couple of weeks.  Using curl, with either address, it eventually redirects to the following (in the response, it says permanently):  

[https://downloads.sourceforge.net/project/omniorb/omniORB/omniORB-4.2.0/omniORB-4.2.0.tar.bz2
](https://downloads.sourceforge.net/project/omniorb/omniORB/omniORB-4.2.0/omniORB-4.2.0.tar.bz2)

That's probably the safe bet if they prune the redirects at some point.  I'm away from my build system.  Can you confirm this address works for you as well (in the recipe)?

**Comment by chris-jo** [comment]
I tested it. It works as well.

**Comment by btgoodwin** [comment]
Great, thanks for your help!  If you have a PR against the krogoth branch, I'll bring it in.  Otherwise I'll handle it Monday.

**Comment by chris-jo** [comment]
OK, maybe it is just a networking issue of my company.

**Comment by btgoodwin** [comment]
If you're still on this or have an easy means to test this (since `http` is working fine for me), would you be able to try this in the recipe:

    SRC_URI = "${SOURCEFORGE_MIRROR}/omniorb/omniORB-4.2.0.tar.bz2;name=omniORB420tarbz2"

With any luck, this would be a good fix for the recipe that works for your situation as well as anyone else who gets blocked trying to use `http`.

**Comment by chris-jo** [comment]
I tested it, there is the same issue because it aims to the http mirror.

```
WARNING: omniorb-4.2.0-r0 do_fetch: Failed to fetch URL http://downloads.sourceforge.net/omniorb/omniORB-4.2.0.tar.bz2;name=omniORB420tarbz2, attempting MIRRORS if available
ERROR: omniorb-4.2.0-r0 do_fetch: Fetcher failure: Fetch command failed with exit code 8, output:
http://downloads.sourceforge.net/omniorb/omniORB-4.2.0.tar.bz2:
2017-02-14 07:28:54 ERROR 403: Forbidden.

ERROR: omniorb-4.2.0-r0 do_fetch: Function failed: Fetcher failure for URL: 'http://downloads.sourceforge.net/omniorb/omniORB-4.2.0.tar.bz2;name=omniORB420tarbz2'. Unable to fetch URL from any source.
ERROR: Logfile of failure stored in: /scratch/yocto_out/tmp-joc-imx6/work/cortexa9hf-neon-poky-linux-gnueabi/omniorb/4.2.0-r0/temp/log.do_fetch.31396
ERROR: Task 0 (/liccon3/git/yocto/meta-redhawk-sdr/recipes-deps/omniorb/omniorb_4.2.0.bb, do_fetch) failed with exit code '1'
```
