### ISSUE TITLE
redhawk-waveform class and EXPORT_FUNCTIONS is illegal

### ISSUE THREAD

**Issue by btgoodwin** [Geontech/meta-redhawk-sdr#45]
Since the class name has a hyphen, we cannot export the do_install task for users to override.  This applies to any release.

Fixes include:

1. Eliminate the `EXPORT_FUNCTIONS` from `redhawk-waveform.bbclass` since really there's only one way to install a waveform.
2. Rename `redhawk-waveform.bbclass` to remove the hyphen (e.g., `redhawk_waveform.bbclass`), which makes it "odd" compared to the other class names.  So then, should we rename them all?

**Comment by btgoodwin** [comment]
@jtalbri @jschindehette @rodrigo455 Any thoughts on the above solutions?  I ran into this today when building a stand-alone system with waveforms.  I'm leaning towards removing the `EXPORT_FUNCTIONS` since renaming the classes would break downstream dependent layers.

**Comment by jschindehette** [comment]
I would normally lean toward renaming the classes, but if keeping compatibility is a higher priority, then we should remove the `EXPORT_FUNCTIONS`.

**Comment by btgoodwin** [comment]
Closed for rocko and thud by #49 and #50, respectively.
