### ISSUE TITLE
Switch from python to python3 for Omniorb

### ISSUE THREAD

**Issue by abogani** [Geontech/meta-redhawk-sdr#56]

**Comment by btgoodwin** [comment]
The REDHAWK core framework requires python 2 at this time.  Even though python 2 is set to deprecate next year, it is still going to "be around" thanks to REDHAT and CentOS communities (which is the main, targeted OS for REDHAWK releases that we track).  Until REDHAWK migrates to python3, we won't be able to migrate either.  I apologize for the inconvenience.

Are you using this layer only for OmniORB or are you also building REDHAWK?

**Comment by abogani** [comment]
Hi @btgoodwin,

I'm using this layer for OmniORB recipe only at the moment.

Thanks for that!

**Comment by btgoodwin** [comment]
You're welcome.  Please feel free to duplicate/extend the recipe to support
python3.  I've been considering submitting patches to get some of our
dependency recipes into openembedded or poky for this reason.

**Comment by abogani** [comment]
I'll create a new OmniORB recipe from scratch due to incompatibility licences. Thanks anyway!
