### ISSUE TITLE
Addeding meta-redhawk-sdr to yocto build

### ISSUE THREAD

**Issue by NayanaAnand** [Geontech/meta-redhawk-sdr#57]
Hi,

I have fallowed the steps for development toolkit from "BSP-Yocto-TISDK-AM57xx-PD18.1.0 Quickstart - PHYTEC Wiki ---> https://wiki.phytec.com/productinfo/phycore-am57x/bsp-yocto-tisdk-am57xx/bsp-yocto-tisdk-am57xx-pd18-2-0-quickstart/bsp-yocto-tisdk-am57xx-pd18-1-0-quickstart" and yocto build is working well.

I have target to add new meta layer "meta-redhawk-sdr" package to existing meta layers.
So, i have cloned redhawk package from 'geotech' git hub and try to build.

I added new meta layer in 'build/conf/bblayers.conf'
:${BSPDIR}/sources/meta-redhawk-sdr \

The build as completed but i didn't find any process included from new package, as per new package (attachment - README.md) process called "Domain and Device" manager task should be seen in process list.

But i didn't find those.

Can anyone help me out in this, how to bring up the process in build and should automatically boot when board is powered on.

The log after the board power on attached above.
[Attachments.zip](https://github.com/Geontech/meta-redhawk-sdr/files/4070553/Attachments.zip)

Regards,
Nayana

**Comment by btgoodwin** [comment]
FWIW, adding the layer to your `bblayers.conf` only exposes the contents of that layer to the build system.  You would still need to build the individual packages or include them into your image's definition (towards the end of that README, we mention the `redhawk-gpp-image` target which installs a device manager and GPP).  You can find a list of package groups and images [here](https://github.com/Geontech/meta-redhawk-sdr/tree/master/recipes-core), however I think you're going to run into other problems.

I reviewed the link you provided, and traced the version of Yocto down to [this line](https://stash.phytec.com/projects/PUB/repos/manifests-phytec/browse/PD18.1.0.xml?at=refs%2Fheads%2Fam57xx#5), which indicates their build is back on Morty.  The current master branch of meta-redhawk-sdr is a more recent Rocko branch, which is still fairly old but for some customers is still their "latest" for several platforms.  (We have internally tested up through Warrior, which is why there is a _warrior_ branch on our repository.)

All that to say: you are likely to run into friction trying to use our more recent layer with an older version of Yocto (upstream packages change, variables become obsolete, etc.).  Since you've already been able to run your build with the layer being parsed without error, you might want to try running `bitbake redhawk-test-image` to see if it can build all of the core framework, components, and softpkgs.  That image should boot with the OmniNames and OmniEvents services running (you'll see init.d messages right before the login).  You should then be able to treat it like a typical REDHAWK installation (i.e., `nodeBooter -D` would bring up the REDHAWK_DEV domain).

Cheers,

Thomas

Edit: One more thing.  In 2019 we started following the Yocto industry practice of release branch names.  The "master" has been maintained for historical reasons, the release branches are the ones being updated.  Specifically rocko, thud, and warrior.  We have some details of what all else changed listed in [this blog post](https://geontech.com/embedded-redhawk-2019/).

**Comment by NayanaAnand** [comment]
Hi Thomas,

Thank you for the update.

I have followed the steps to build the redhawk-gpp-image as given in README.md. and checkout the branch 'pyro' and set the REDHAWK_PROCESSOR=Cortex-A15
As per my requirement, modified (contrib/scripts/build-image.sh) as below:
 MACHINE = 'am572x'
 
When i give bitbake redhawk-gpp-image, it is building for framework.

But i have seen below Eroor:
| /bin/grep: /opt/PHYTEC_BSPs/yocto_ti/build/arago-tmp-external-linaro-toolchain/sysroots/am57xx-phycore-rdk/home/tcwg-buildslave/workspace/tcwg-make-release/label/tcwg-x86_64-ex40/target/arm-linux-gnueabihf/_build/builds/destdir/x86_64-unknown-linux-gnu/arm-linux-gnueabihf/lib/libstdc++.la: No such file or directory
| sed: can't read /opt/PHYTEC_BSPs/yocto_ti/build/arago-tmp-external-linaro-toolchain/sysroots/am57xx-phycore-rdk/home/tcwg-buildslave/workspace/tcwg-make-release/label/tcwg-x86_64-ex40/target/arm-linux-gnueabihf/_build/builds/destdir/x86_64-unknown-linux-gnu/arm-linux-gnueabihf/lib/libstdc++.la: No such file or directory
| arm-linux-gnueabi-libtool:   error: '/opt/PHYTEC_BSPs/yocto_ti/build/arago-tmp-external-linaro-toolchain/sysroots/am57xx-phycore-rdk/home/tcwg-buildslave/workspace/tcwg-make-release/label/tcwg-x86_64-ex40/target/arm-linux-gnueabihf/_build/builds/destdir/x86_64-unknown-linux-gnu/arm-linux-gnueabihf/lib/libstdc++.la' is not a valid libtool archive
| make[3]: *** [libossieidl.la] Error 1
| make[3]: Leaving directory `/opt/PHYTEC_BSPs/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/armv7ahf-neon-linux-gnueabi/redhawk/2.0.6-r2/git/redhawk-core-framework/redhawk/src/base/framework/idl'
| make[2]: *** [all] Error 2
| make[2]: Leaving directory `/opt/PHYTEC_BSPs/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/armv7ahf-neon-linux-gnueabi/redhawk/2.0.6-r2/git/redhawk-core-framework/redhawk/src/base/framework/idl'
| make[1]: *** [all-recursive] Error 1
| make[1]: Leaving directory `/opt/PHYTEC_BSPs/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/armv7ahf-neon-linux-gnueabi/redhawk/2.0.6-r2/git/redhawk-core-framework/redhawk/src/base'
| make: *** [all-recursive] Error 1
| ERROR: oe_runmake failed
| ERROR: Function failed: do_compile (log file is located at /opt/PHYTEC_BSPs/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/armv7ahf-neon-linux-gnueabi/redhawk/2.0.6-r2/temp/log.do_compile.29856)
ERROR: Task 2187 (/opt/PHYTEC_BSPs/yocto_ti/sources/meta-redhawk-sdr/recipes-core-framework/redhawk/redhawk_2.0.6.bb, do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 2374 tasks of which 2214 didn't need to be rerun and 1 failed.
Waiting for 0 running tasks to finish:

Summary: 1 task failed:
  /opt/PHYTEC_BSPs/yocto_ti/sources/meta-redhawk-sdr/recipes-core-framework/redhawk/redhawk_2.0.6.bb, do_compile
Summary: There were 5 WARNING messages shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.

Can you please suggest me the further procedure.

Regards,
Nayana

**Comment by btgoodwin** [comment]
The errors are saying that the libstdc++.la library doesn't exist so libtool fails, which is odd since you've probably built other packages against that library.  Never the less, this can happen if the toolchain doesn't build properly, for example.  Another reason could be that the necessary dependency (DEPENDS) is missing from the `redhawk` package, but I rather doubt that.  You might try identifying where that file is produced originally (i.e., the package's build directory) to verify it is actually being built.

It has been a few years since I've known anyone building against Pyro.  We're most consistently building on _rocko_ and _thud_ branches because of Xilinx and Intel Stratix 10 targets in the last year or so.

**Comment by NayanaAnand** [comment]
Hi Thomas,

The Error shows, the build is searching for "libstdc++.la" in path "build/arago-tmp-external-linaro-toolchain/sysroots/am57xx-phycore-rdk/home/tcwg-buildslave/workspace/tcwg-make-release/label/tcwg-x86_64-ex40/target/arm-linux-gnueabihf/_build/builds/destdir/x86_64-unknown-linux-gnu/arm-linux-gnueabihf/lib".

ERROR ::
| /bin/grep: /opt/PHYTEC_BSPs/yocto_ti/build/arago-tmp-external-linaro-toolchain/sysroots/am57xx-phycore-rdk/home/tcwg-buildslave/workspace/tcwg-make-release/label/tcwg-x86_64-ex40/target/arm-linux-gnueabihf/_build/builds/destdir/x86_64-unknown-linux-gnu/arm-linux-gnueabihf/lib/libstdc++.la: No such file or directory
| sed: can't read /opt/PHYTEC_BSPs/yocto_ti/build/arago-tmp-external-linaro-toolchain/sysroots/am57xx-phycore-rdk/home/tcwg-buildslave/workspace/tcwg-make-release/label/tcwg-x86_64-ex40/target/arm-linux-gnueabihf/_build/builds/destdir/x86_64-unknown-linux-gnu/arm-linux-gnueabihf/lib/libstdc++.la: No such file or directory
| arm-linux-gnueabi-libtool:   error: '/opt/PHYTEC_BSPs/yocto_ti/build/arago-tmp-external-linaro-toolchain/sysroots/am57xx-phycore-rdk/home/tcwg-buildslave/workspace/tcwg-make-release/label/tcwg-x86_64-ex40/target/arm-linux-gnueabihf/_build/builds/destdir/x86_64-unknown-linux-gnu/arm-linux-gnueabihf/lib/libstdc++.la' is not a valid libtool archive


But from the previous successful build, i can see the libstdc++.la found in other places given below and doubt is why the build is checking for file only the above path.
i didn't find the folder called "home/tcwg-buildslave" in my build directory.

cyient@INBE1E-DWL292AV:/opt/PHYTEC_BSPs/yocto_ti/build$ find . -name "libstdc++.la"
./arago-tmp-external-linaro-toolchain/sysroots/x86_64-nativesdk-arago-linux/tmp/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy/sysroots/x86_64-arago-linux/usr/lib/libstdc++.la
./arago-tmp-external-linaro-toolchain/sysroots/am57xx-phycore-rdk/lib/libstdc++.la
./arago-tmp-external-linaro-toolchain/sysroots/am57xx-phycore-rdk/usr/include/glibc-locale-internal-armv7ahf-neon-linux-gnueabi/lib/libstdc++.la
./arago-tmp-external-linaro-toolchain/work/x86_64-linux/protobuf-native/2.6.1+gitAUTOINC+bba83652e1-r0/git/src/solaris/libstdc++.la
./arago-tmp-external-linaro-toolchain/work/am572x_phycore_rdk-linux-gnueabi/tisdk-rootfs-image/1.0-r0.tisdk1/rootfs/lib/libstdc++.la
./arago-tmp-external-linaro-toolchain/work/x86_64-nativesdk-arago-linux/external-linaro-sdk-toolchain/1.0-r5/image/tmp/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy/sysroots/x86_64-arago-linux/usr/arm-linux-gnueabihf/lib/libstdc++.la
./arago-tmp-external-linaro-toolchain/work/x86_64-nativesdk-arago-linux/external-linaro-sdk-toolchain/1.0-r5/packages-split/gcc-cross-canadian-arm/tmp/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy/sysroots/x86_64-arago-linux/usr/arm-linux-gnueabihf/lib/libstdc++.la
./arago-tmp-external-linaro-toolchain/work/x86_64-nativesdk-arago-linux/external-linaro-sdk-toolchain/1.0-r5/package/tmp/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy/sysroots/x86_64-arago-linux/usr/arm-linux-gnueabihf/lib/libstdc++.la
./arago-tmp-external-linaro-toolchain/work/x86_64-nativesdk-arago-linux/nativesdk-gcc-runtime/linaro-5.3-r2016.02/sysroot-destdir/tmp/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy/sysroots/x86_64-arago-linux/usr/lib/libstdc++.la
./arago-tmp-external-linaro-toolchain/work/am57xx_phycore_rdk-linux-gnueabi/tisdk-rootfs-image/1.0-r0.tisdk1/rootfs/lib/libstdc++.la
./arago-tmp-external-linaro-toolchain/work/armv7ahf-neon-linux-gnueabi/protobuf/2.6.1+gitAUTOINC+bba83652e1-r0/git/src/solaris/libstdc++.la
./arago-tmp-external-linaro-toolchain/work/armv7ahf-neon-linux-gnueabi/external-linaro-toolchain/2016.02-r0.arago32/sysroot-destdir/lib/libstdc++.la
./arago-tmp-external-linaro-toolchain/work/armv7ahf-neon-linux-gnueabi/external-linaro-toolchain/2016.02-r0.arago32/sysroot-destdir/usr/include/glibc-locale-internal-armv7ahf-neon-linux-gnueabi/lib/libstdc++.la

Can you tell me, is there any way to change that path?

Regards,
Nayana

**Comment by NayanaAnand** [comment]
Hi Thomas,

I have tried source from rocko and thud also and added Error log below....

Log: 
ERROR: Nothing RPROVIDES 'python-threading-native' (but virtual:native:/opt/PHYTEC_BSPs/yocto_ti/sources/meta-redhawk-sdr/recipes-core/core-framework/redhawk_2.2.3.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'python-threading-native' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python-threading-native']
NOTE: Runtime target 'gpp-node' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gpp-node', 'redhawk-native', 'python-threading-native']
ERROR: Required build target 'redhawk-gpp-image' has no buildable providers.
Missing or unbuildable dependency chain was: ['redhawk-gpp-image', 'gpp-node', 'redhawk-native', 'python-threading-native']

Summary: There were 2 WARNING messages shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code


Above error is same for even warrior branch also.
For krogoth and pyro branch i am facing libstdc++.la file not found in required path....please reffer above comment for library issue.

Note ::
Can you suggest me which branch i can go ahead for yocto-morty build.

Regards,
Nayana

**Comment by btgoodwin** [comment]
Hi Nayana,

I answered both of these in your other issue thread.  A lot of these problems are related to mixing layer versions since significant changes happened in the last few years (most of which are listed in the Yocto change log of each mega manual release).

Based on the paths you mentioned for the library file, some of those are the toolchain for cross-canadian builds, some are for native, some are for target, etc.  The build environment, based on the recipe's DEPENDS, should have its various build variables (e.g., CFLAGS) pre-configured to look at the correct paths so that linking can occur.  If something about the build environment misconfigures those paths, then you would see things like the above.

If your vendor doesn't provide support directly for a newer Yocto release, your best bet is to pull the vendor BSP forward to a newer release of Yocto (without meta-redhawk-sdr present in the bblayers) and then once that is working, build packages from the compatible release of meta-redhawk-sdr.  

Your other alternative is to try our other tagged releases until something works with Morty.  The v2.0.5-0 release was against krogoth (predates morty by a release), and the first mention of being tested on Pyro is at v2.0.6-1 (which postdates morty by a release).

**Comment by btgoodwin** [comment]
Closing this issue since it's likely related to mixing yocto release versions.  If you do get your build on a single release, supported by meta-redhawk-sdr, and still have problems, please feel free to reply here or open another issue.

**Comment by shravan56** [comment]
Hi Thomas,
Even i also fallowed the steps for development toolkit from "BSP-Yocto-TISDK-AM57xx-PD18.1.0 Quickstart - PHYTEC Wiki ---> https://wiki.phytec.com/productinfo/phycore-am57x/bsp-yocto-tisdk-am57xx/bsp-yocto-tisdk-am57xx-pd18-2-0-quickstart/bsp-yocto-tisdk-am57xx-pd18-1-0-quickstart" .

I have target to add new meta layer "meta-redhawk-sdr" package to existing meta layers.
So, i have cloned redhawk package from 'geotech' git hub and try to build.

I added new meta layer in 'build/conf/bblayers.conf'
:${BSPDIR}/sources/meta-redhawk-sdr \

And after running command "MACHINE=am57xx-phycore-rdk bitbake arago-core-tisdk-image"
iam getting below error (for command : "bitbake redhawk-gpp-image" geting same error)

Error:
/opt/phytec_bsps/yocto_ti/build$ MACHINE=am57xx-phycore-rdk bitbake arago-core-tisdk-image
Loading cache: 100% |###################################################################################################################################################| ETA:  00:00:00
Loaded 2919 entries from dependency cache.
Parsing recipes: 100% |#################################################################################################################################################| Time: 00:00:00
Parsing of 2320 .bb files complete (2319 cached, 1 parsed). 2919 targets, 453 skipped, 0 masked, 0 errors.
WARNING: No recipes available for:
  /opt/phytec_bsps/yocto_ti/sources/meta-arago/meta-arago-distro/recipes-security/optee/optee-os_git.bbappend
  /opt/phytec_bsps/yocto_ti/sources/meta-processor-sdk/recipes-core/udev/udev_182.bbappend
  /opt/phytec_bsps/yocto_ti/sources/meta-phytec/meta-phytec-ti/recipes-support/cpuset/cpuset_1.5.6.bbappend
WARNING: No bb files matched BBFILE_PATTERN_phytec '^/opt/phytec_bsps/yocto_ti/sources/meta-phytec/common/'
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION        = "1.30.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "Ubuntu-14.04"
TARGET_SYS        = "arm-linux-gnueabi"
MACHINE           = "am57xx-phycore-rdk"
DISTRO            = "arago"
DISTRO_VERSION    = "2016.10"
TUNE_FEATURES     = "arm armv7a vfp thumb neon       callconvention-hard"
TARGET_FPU        = "hard"
meta-processor-sdk = "HEAD:3678d672c9c47a646897286281d4260ac4ace960"
meta-arago-distro 
meta-arago-extras = "HEAD:76381bbc10b93ffc6c014154814872b170b93796"
meta-qt5          = "HEAD:2b1871f0d139dc3caaa779a32a1931409c245a36"
meta-networking   
meta-python       
meta-ruby         
meta-oe           = "HEAD:851a064b53dca3b14dd33eaaaca9573b1a36bf0e"
meta-ti           = "HEAD:d8aa76970a0ba48762c631dfd79dbed49222373b"
meta-linaro-toolchain = "HEAD:9b616ce6d4293387d254f36800389b2910895420"
meta              = "HEAD:28da89a20b70f2bf0c85da6e8af5d94a3b7d76c9"
meta-phytec       
meta-phytec-ti    = "HEAD:086a659eb42b85ca68d21f4bee8eb51cb9ea3019"
meta-redhawk-sdr  = "thud:2e3f30e1af435b995ed47a71837b79ef2fe7144c"

NOTE: Preparing RunQueue
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
ERROR: omniorb-native-4.2.3-r0 do_compile: oe_runmake failed
ERROR: omniorb-native-4.2.3-r0 do_compile: Function failed: do_compile (log file is located at /opt/phytec_bsps/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/x86_64-linux/omniorb-native/4.2.3-r0/temp/log.do_compile.15154)
ERROR: Logfile of failure stored in: /opt/phytec_bsps/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/x86_64-linux/omniorb-native/4.2.3-r0/temp/log.do_compile.15154
Log data follows:
| DEBUG: Executing shell function do_compile
| NOTE: make -j 4
| making export in ./src...
| make[1]: Entering directory `/opt/phytec_bsps/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/x86_64-linux/omniorb-native/4.2.3-r0/build/src'
| making export in src/tool...
| make[2]: Entering directory `/opt/phytec_bsps/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/x86_64-linux/omniorb-native/4.2.3-r0/build/src/tool'
| making export in src/tool/omkdepend...
| make[3]: Entering directory `/opt/phytec_bsps/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/x86_64-linux/omniorb-native/4.2.3-r0/build/src/tool/omkdepend'
| File omkdepend hasn't changed.
| make[3]: Leaving directory `/opt/phytec_bsps/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/x86_64-linux/omniorb-native/4.2.3-r0/build/src/tool/omkdepend'
| making export in src/tool/omniidl...
| make[3]: Entering directory `/opt/phytec_bsps/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/x86_64-linux/omniorb-native/4.2.3-r0/build/src/tool/omniidl'
| making export in src/tool/omniidl/cxx...
| Traceback (most recent call last):
|   File "<string>", line 1, in <module>
|   File "/opt/phytec_bsps/yocto_ti/build/arago-tmp-external-linaro-toolchain/sysroots/x86_64-linux/usr/lib/python2.7/distutils/sysconfig.py", line 22, in <module>
|     PREFIX = os.path.normpath(sys.prefix).replace( os.getenv("BUILD_SYS"), os.getenv("HOST_SYS") )
| TypeError: expected a string or other character buffer object
| Traceback (most recent call last):
|   File "<string>", line 1, in <module>
|   File "/opt/phytec_bsps/yocto_ti/build/arago-tmp-external-linaro-toolchain/sysroots/x86_64-linux/usr/lib/python2.7/distutils/sysconfig.py", line 22, in <module>
|     PREFIX = os.path.normpath(sys.prefix).replace( os.getenv("BUILD_SYS"), os.getenv("HOST_SYS") )
| TypeError: expected a string or other character buffer object
| make[4]: Entering directory `/opt/phytec_bsps/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/x86_64-linux/omniorb-native/4.2.3-r0/build/src/tool/omniidl/cxx'
| making export in src/tool/omniidl/cxx/cccp...
| make[5]: Entering directory `/opt/phytec_bsps/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/x86_64-linux/omniorb-native/4.2.3-r0/build/src/tool/omniidl/cxx/cccp'
| File omnicpp hasn't changed.
| make[5]: Leaving directory `/opt/phytec_bsps/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/x86_64-linux/omniorb-native/4.2.3-r0/build/src/tool/omniidl/cxx/cccp'
| g++  -c -isystem/opt/phytec_bsps/yocto_ti/build/arago-tmp-external-linaro-toolchain/sysroots/x86_64-linux/usr/include -O2 -pipe -Wall -Wno-unused -fexceptions  -isystem/opt/phytec_bsps/yocto_ti/build/arago-tmp-external-linaro-toolchain/sysroots/x86_64-linux/usr/include -I -DPYTHON_INCLUDE="<Python.h>" -DPYTHON_THREAD_INC="<pythread.h>" -DIDLMODULE_VERSION="\"0x2630\"" -fPIC -I. -I../../../../../omniORB-4.2.3/src/tool/omniidl/cxx -I../../../../include -I../../../../../omniORB-4.2.3/include -D__OSVERSION__=2 -D__linux__ -D__x86_64__ -o idlpython.o ../../../../../omniORB-4.2.3/src/tool/omniidl/cxx/idlpython.cc
| ../../../../../omniORB-4.2.3/src/tool/omniidl/cxx/idlpython.cc:31:12: error: #include expects "FILENAME" or <FILENAME>
|  #  include PYTHON_INCLUDE
|             ^
| ../../../../../omniORB-4.2.3/src/tool/omniidl/cxx/idlpython.cc:47:6: error: #error "omniidl requires Python 1.5.2 or higher"
|  #    error "omniidl requires Python 1.5.2 or higher"
|       ^
| ../../../../../omniORB-4.2.3/src/tool/omniidl/cxx/idlpython.cc:99:15: error: 'PyObject' does not name a type
|  static inline PyObject* PyString_FromChar(unsigned char c)
|                ^
| ../../../../../omniORB-4.2.3/src/tool/omniidl/cxx/idlpython.cc:150:3: error: 'PyObject' does not name a type
|    PyObject* result() { return result_; }
|    ^
| ../../../../../omniORB-4.2.3/src/tool/omniidl/cxx/idlpython.cc:152:10: error: 'PyObject' does not name a type
|    static PyObject* scopedNameToList(const ScopedName* sn);
|           ^
.....
....
....
| ../../../../../omniORB-4.2.3/src/tool/omniidl/cxx/idlpython.cc:1532:15: error: 'm' was not declared in this scope
|      PyObject* m = Py_InitModule((char*)"_omniidl", omniidl_methods);
|                ^
| ../../../../../omniORB-4.2.3/src/tool/omniidl/cxx/idlpython.cc:1532:52: error: 'omniidl_methods' was not declared in this scope
|      PyObject* m = Py_InitModule((char*)"_omniidl", omniidl_methods);
|                                                     ^
| ../../../../../omniORB-4.2.3/src/tool/omniidl/cxx/idlpython.cc:1532:67: error: 'Py_InitModule' was not declared in this scope
|      PyObject* m = Py_InitModule((char*)"_omniidl", omniidl_methods);
|                                                                    ^
| ../../../../../omniORB-4.2.3/src/tool/omniidl/cxx/idlpython.cc:1534:44: error: 'PyString_FromString' was not declared in this scope
|        PyString_FromString(IDLMODULE_VERSION));
|                                             ^
| ../../../../../omniORB-4.2.3/src/tool/omniidl/cxx/idlpython.cc:1534:45: error: 'PyObject_SetAttrString' was not declared in this scope
|        PyString_FromString(IDLMODULE_VERSION));
|                                              ^
| make[4]: *** [idlpython.o] Error 1
| make[4]: Leaving directory `/opt/phytec_bsps/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/x86_64-linux/omniorb-native/4.2.3-r0/build/src/tool/omniidl/cxx'
| make[3]: *** [export] Error 1
| make[3]: Leaving directory `/opt/phytec_bsps/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/x86_64-linux/omniorb-native/4.2.3-r0/build/src/tool/omniidl'
| make[2]: *** [export] Error 1
| make[2]: Leaving directory `/opt/phytec_bsps/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/x86_64-linux/omniorb-native/4.2.3-r0/build/src/tool'
| make[1]: *** [export] Error 1
| make[1]: Leaving directory `/opt/phytec_bsps/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/x86_64-linux/omniorb-native/4.2.3-r0/build/src'
| make: *** [all] Error 1
| ERROR: oe_runmake failed
| ERROR: Function failed: do_compile (log file is located at /opt/phytec_bsps/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/x86_64-linux/omniorb-native/4.2.3-r0/temp/log.do_compile.15154)
ERROR: Task 7988 (virtual:native:/opt/phytec_bsps/yocto_ti/sources/meta-redhawk-sdr/recipes-deps/omniorb/omniorb_4.2.3.bb, do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 2652 tasks of which 2646 didn't need to be rerun and 1 failed.
Waiting for 0 running tasks to finish:

Summary: 1 task failed:
  virtual:native:/opt/phytec_bsps/yocto_ti/sources/meta-redhawk-sdr/recipes-deps/omniorb/omniorb_4.2.3.bb, do_compile
Summary: There were 2 WARNING messages shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.


Is i missed to add any package..or lib path ...?
Please suggest me to overcome this issue and what mistake done from my side...?

regards
shravan

**Comment by btgoodwin** [comment]
That link you provided doesn't work for me.

Judging by that bitbake intro log though, between the Ubuntu 14.04 and 2016 distro, I'm going to venture the linked build instructions are much older than this layer supports, probably much older than `thud` would use.  As with the OP, I recommend not mixing layer versions in Yocto.
