### ISSUE TITLE
Missing or unbuildable dependency chain was: ['redhawk-gpp-image', 'gpp-node', 'redhawk-native', 'python-threading-native']

### ISSUE THREAD

**Issue by NayanaAnand** [Geontech/meta-redhawk-sdr#58]
Hi,

I have YOCTO build setup as per the link below :
https://wiki.phytec.com/productinfo/phycore-am57x/bsp-yocto-tisdk-am57xx/bsp-yocto-tisdk-am57xx-pd18-2-0-quickstart/bsp-yocto-tisdk-am57xx-pd17-1-1-quickstart

As per the above setup, the build is on morty.

Target :
Want to include "meta-redhawk-sdr" to source.

I have fallowed steps to add meta-redhawk layer from below link :
https://github.com/Geontech/meta-redhawk-sdr

Branch : 
I have tried rocko, thud and warrior. I have seen same ERROR in all the branch as mentioned.

ERROR Log:
cyient@INBE1E-DWL292AV:/opt/PHYTEC_BSPs/yocto_ti/build$ bitbake redhawk-gpp-image
Loading cache: 100% |########################################################################################################################################################################| ETA:  00:00:00
Loaded 2937 entries from dependency cache.
WARNING: No recipes available for:
  /opt/PHYTEC_BSPs/yocto_ti/sources/meta-arago/meta-arago-distro/recipes-security/optee/optee-os_git.bbappend
  /opt/PHYTEC_BSPs/yocto_ti/sources/meta-processor-sdk/recipes-core/udev/udev_182.bbappend
  /opt/PHYTEC_BSPs/yocto_ti/sources/meta-phytec/meta-phytec-ti/recipes-support/cpuset/cpuset_1.5.6.bbappend
WARNING: No bb files matched BBFILE_PATTERN_phytec '^/opt/PHYTEC_BSPs/yocto_ti/sources/meta-phytec/common/'
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing RPROVIDES 'python-threading-native' (but virtual:native:/opt/PHYTEC_BSPs/yocto_ti/sources/meta-redhawk-sdr/recipes-core/core-framework/redhawk_2.2.3.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'python-threading-native' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python-threading-native']
NOTE: Runtime target 'gpp-node' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['gpp-node', 'redhawk-native', 'python-threading-native']
ERROR: Required build target 'redhawk-gpp-image' has no buildable providers.
Missing or unbuildable dependency chain was: ['redhawk-gpp-image', 'gpp-node', 'redhawk-native', 'python-threading-native']

Summary: There were 2 WARNING messages shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.

Even i tried executing "bitbake redhawk-test-image", the ERROR is same.

For Branch :
pyro and krogoth, i have facing library issue as below.

ERROR LOG:
cyient@INBE1E-DWL292AV:/opt/PHYTEC_BSPs/yocto_ti/build$ bitbake redhawk-gpp-image
Loading cache: 100% |########################################################################################################################################################################| ETA:  00:00:00
Loaded 2936 entries from dependency cache.
WARNING: No recipes available for:
  /opt/PHYTEC_BSPs/yocto_ti/sources/meta-arago/meta-arago-distro/recipes-security/optee/optee-os_git.bbappend
  /opt/PHYTEC_BSPs/yocto_ti/sources/meta-processor-sdk/recipes-core/udev/udev_182.bbappend
  /opt/PHYTEC_BSPs/yocto_ti/sources/meta-phytec/meta-phytec-ti/recipes-support/cpuset/cpuset_1.5.6.bbappend
WARNING: No bb files matched BBFILE_PATTERN_phytec '^/opt/PHYTEC_BSPs/yocto_ti/sources/meta-phytec/common/'
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION        = "1.30.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "Ubuntu-14.04"
TARGET_SYS        = "arm-linux-gnueabi"
MACHINE           = "am57xx-phycore-rdk"
DISTRO            = "arago"
DISTRO_VERSION    = "2016.10"
TUNE_FEATURES     = "arm armv7a vfp thumb neon       callconvention-hard"
TARGET_FPU        = "hard"
meta-processor-sdk = "morty:3678d672c9c47a646897286281d4260ac4ace960"
meta-arago-distro 
meta-arago-extras = "HEAD:76381bbc10b93ffc6c014154814872b170b93796"
meta-qt5          = "HEAD:2b1871f0d139dc3caaa779a32a1931409c245a36"
meta-networking   
meta-python       
meta-ruby         
meta-oe           = "morty:851a064b53dca3b14dd33eaaaca9573b1a36bf0e"
meta-ti           = "HEAD:d8aa76970a0ba48762c631dfd79dbed49222373b"
meta-linaro-toolchain = "HEAD:9b616ce6d4293387d254f36800389b2910895420"
meta              = "HEAD:28da89a20b70f2bf0c85da6e8af5d94a3b7d76c9"
meta-phytec       
meta-phytec-ti    = "HEAD:086a659eb42b85ca68d21f4bee8eb51cb9ea3019"
meta-redhawk-sdr  = "pyro:06ff489191194292aed6386407602049e07ec887"
meta-filesystems  = "morty:851a064b53dca3b14dd33eaaaca9573b1a36bf0e"

NOTE: Preparing RunQueue
WARNING: /opt/PHYTEC_BSPs/yocto_ti/sources/meta-phytec/meta-phytec-ti/recipes-kernel/linux/linux-phytec-ti_4.4.bb.do_compile is tainted from a forced run
WARNING: /opt/PHYTEC_BSPs/yocto_ti/sources/meta-phytec/meta-phytec-ti/recipes-bsp/u-boot/u-boot-phytec_2016.05.bb.do_compile is tainted from a forced run
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
ERROR: redhawk-2.0.6-r2 do_compile: oe_runmake failed
ERROR: redhawk-2.0.6-r2 do_compile: Function failed: do_compile (log file is located at /opt/PHYTEC_BSPs/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/armv7ahf-neon-linux-gnueabi/redhawk/2.0.6-r2/temp/log.do_compile.11636)
ERROR: Logfile of failure stored in: /opt/PHYTEC_BSPs/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/armv7ahf-neon-linux-gnueabi/redhawk/2.0.6-r2/temp/log.do_compile.11636
Log data follows:
| DEBUG: SITE files ['endian-little', 'bit-32', 'arm-common', 'arm-32', 'common-linux', 'common-glibc', 'arm-linux', 'arm-linux-gnueabi', 'common']
| DEBUG: Executing shell function do_compile
| NOTE: make -j 4
| Making all in acinclude
| make[1]: Entering directory `/opt/PHYTEC_BSPs/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/armv7ahf-neon-linux-gnueabi/redhawk/2.0.6-r2/git/redhawk-core-framework/redhawk/src/acinclude'
| make[1]: Nothing to be done for `all'.
| make[1]: Leaving directory `/opt/PHYTEC_BSPs/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/armv7ahf-neon-linux-gnueabi/redhawk/2.0.6-r2/git/redhawk-core-framework/redhawk/src/acinclude'
| Making all in etc
| make[1]: Entering directory `/opt/PHYTEC_BSPs/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/armv7ahf-neon-linux-gnueabi/redhawk/2.0.6-r2/git/redhawk-core-framework/redhawk/src/etc'
| make[1]: Nothing to be done for `all'.
| make[1]: Leaving directory `/opt/PHYTEC_BSPs/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/armv7ahf-neon-linux-gnueabi/redhawk/2.0.6-r2/git/redhawk-core-framework/redhawk/src/etc'
| Making all in base
| make[1]: Entering directory `/opt/PHYTEC_BSPs/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/armv7ahf-neon-linux-gnueabi/redhawk/2.0.6-r2/git/redhawk-core-framework/redhawk/src/base'
| Making all in framework/idl
| make[2]: Entering directory `/opt/PHYTEC_BSPs/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/armv7ahf-neon-linux-gnueabi/redhawk/2.0.6-r2/git/redhawk-core-framework/redhawk/src/base/framework/idl'
| make  all-am
| make[3]: Entering directory `/opt/PHYTEC_BSPs/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/armv7ahf-neon-linux-gnueabi/redhawk/2.0.6-r2/git/redhawk-core-framework/redhawk/src/base/framework/idl'
| ../../../arm-linux-gnueabi-libtool  --tag=CXX   --mode=link arm-linux-gnueabihf-g++  -march=armv7-a -marm -mfpu=neon  -mfloat-abi=hard --sysroot=/opt/PHYTEC_BSPs/yocto_ti/build/arago-tmp-external-linaro-toolchain/sysroots/am57xx-phycore-rdk -Wall -Wno-switch -D__arm__ -D__linux__ -D__OSVERSION__=2 -D__arm__ -D__linux__ -D__OSVERSION__=2 -D__arm__ -D__linux__ -D__OSVERSION__=2 -D__arm__ -D__linux__ -D__OSVERSION__=2 -I../../include -isystem/opt/PHYTEC_BSPs/gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include  -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/opt/PHYTEC_BSPs/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/armv7ahf-neon-linux-gnueabi/redhawk/2.0.6-r2=/usr/src/debug/redhawk/2.0.6-r2 -fdebug-prefix-map=/opt/PHYTEC_BSPs/yocto_ti/build/arago-tmp-external-linaro-toolchain/sysroots/x86_64-linux= -fdebug-prefix-map=/opt/PHYTEC_BSPs/yocto_ti/build/arago-tmp-external-linaro-toolchain/sysroots/am57xx-phycore-rdk=  -fpermissive -std=gnu++98 -Wall -version-info 4:0:0 -L/opt/PHYTEC_BSPs/gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/lib -Wl,-rpath-link,/opt/PHYTEC_BSPs/gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/lib -Wl,-O1 -Wl,--hash-style=gnu -o libossieidl.la -rpath /usr/redhawk-sdr/core/lib libossieidl_la-cfSK.lo libossieidl_la-cfDynSK.lo libossieidl_la-DataTypeSK.lo libossieidl_la-DataTypeDynSK.lo libossieidl_la-PortSK.lo libossieidl_la-PortDynSK.lo libossieidl_la-PortTypesSK.lo libossieidl_la-PortTypesDynSK.lo libossieidl_la-StandardEventSK.lo libossieidl_la-StandardEventDynSK.lo libossieidl_la-AggregateDevicesSK.lo libossieidl_la-AggregateDevicesDynSK.lo libossieidl_la-ExtendedEventSK.lo libossieidl_la-ExtendedEventDynSK.lo libossieidl_la-QueryablePortSK.lo libossieidl_la-QueryablePortDynSK.lo libossieidl_la-WellKnownPropertiesSK.lo libossieidl_la-WellKnownPropertiesDynSK.lo libossieidl_la-sandboxSK.lo libossieidl_la-sandboxDynSK.lo libossieidl_la-LogInterfacesSK.lo libossieidl_la-LogInterfacesDynSK.lo libossieidl_la-EventChannelManagerSK.lo libossieidl_la-EventChannelManagerDynSK.lo -lomniORB4 -lomnithread -lomnithread -lomniDynamic4 -lomniORB4 -lomnithread -luuid  -llog4cxx
| /bin/grep: /opt/PHYTEC_BSPs/yocto_ti/build/arago-tmp-external-linaro-toolchain/sysroots/am57xx-phycore-rdk/home/tcwg-buildslave/workspace/tcwg-make-release/label/tcwg-x86_64-ex40/target/arm-linux-gnueabihf/_build/builds/destdir/x86_64-unknown-linux-gnu/arm-linux-gnueabihf/lib/libstdc++.la: No such file or directory
| sed: can't read /opt/PHYTEC_BSPs/yocto_ti/build/arago-tmp-external-linaro-toolchain/sysroots/am57xx-phycore-rdk/home/tcwg-buildslave/workspace/tcwg-make-release/label/tcwg-x86_64-ex40/target/arm-linux-gnueabihf/_build/builds/destdir/x86_64-unknown-linux-gnu/arm-linux-gnueabihf/lib/libstdc++.la: No such file or directory
| arm-linux-gnueabi-libtool:   error: '/opt/PHYTEC_BSPs/yocto_ti/build/arago-tmp-external-linaro-toolchain/sysroots/am57xx-phycore-rdk/home/tcwg-buildslave/workspace/tcwg-make-release/label/tcwg-x86_64-ex40/target/arm-linux-gnueabihf/_build/builds/destdir/x86_64-unknown-linux-gnu/arm-linux-gnueabihf/lib/libstdc++.la' is not a valid libtool archive
| make[3]: *** [libossieidl.la] Error 1
| make[3]: Leaving directory `/opt/PHYTEC_BSPs/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/armv7ahf-neon-linux-gnueabi/redhawk/2.0.6-r2/git/redhawk-core-framework/redhawk/src/base/framework/idl'
| make[2]: *** [all] Error 2
| make[2]: Leaving directory `/opt/PHYTEC_BSPs/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/armv7ahf-neon-linux-gnueabi/redhawk/2.0.6-r2/git/redhawk-core-framework/redhawk/src/base/framework/idl'
| make[1]: *** [all-recursive] Error 1
| make[1]: Leaving directory `/opt/PHYTEC_BSPs/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/armv7ahf-neon-linux-gnueabi/redhawk/2.0.6-r2/git/redhawk-core-framework/redhawk/src/base'
| make: *** [all-recursive] Error 1
| ERROR: oe_runmake failed
| ERROR: Function failed: do_compile (log file is located at /opt/PHYTEC_BSPs/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/armv7ahf-neon-linux-gnueabi/redhawk/2.0.6-r2/temp/log.do_compile.11636)
ERROR: Task 2187 (/opt/PHYTEC_BSPs/yocto_ti/sources/meta-redhawk-sdr/recipes-core-framework/redhawk/redhawk_2.0.6.bb, do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 2208 tasks of which 2204 didn't need to be rerun and 1 failed.
Waiting for 0 running tasks to finish:

Summary: 1 task failed:
  /opt/PHYTEC_BSPs/yocto_ti/sources/meta-redhawk-sdr/recipes-core-framework/redhawk/redhawk_2.0.6.bb, do_compile
Summary: There were 4 WARNING messages shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.

Can anyone help me, which branch of Readhawk is matches with yocto-morty branch and solution for above issues.

Purpose:
Want to bring up the Device and Domain manager of Readhawk when we flash images generated from bitbake.

Regards,
Nayana

**Comment by btgoodwin** [comment]
I apologize for the lack of a _morty_ branch; we haven't had a need to support it.

Consequently, that branch (morty) and the ones immediately following it brought significant reorganization to how builds progress as well as the names of certain things like the python packages (which impacts DEPENDS/RDEPENDS, etc.).  You can find out more details in the mega manual change logs for each release, but the gist is that one's whole build should be compatible with some specific version of the core layers.  So picking the rocko branch of meta-redhawk-sdr as the example, all of your other layers should also be rocko-compatible.  Otherwise, you're more likely to see the above kinds of errors.

My best guess about the libtool error is that the redhawk recipe is missing a DEPENDS against the package that would provide that library.  Unfortunately I won't have the time to attempt a similar build here for a couple weeks, and even then, the build would be stuck back at 2.0.6 and would be missing a lot of the newer features found in the releases we do currently support.

**Comment by btgoodwin** [comment]
Closing this issue since it's likely related to mixing yocto release versions.  If you do get your build on a single release, supported by meta-redhawk-sdr, and still have problems, please feel free to reply here or open another issue.

**Comment by shravan56** [comment]
Hi Thomas,
Even i also fallowed the steps for development toolkit from "BSP-Yocto-TISDK-AM57xx-PD18.1.0 Quickstart - PHYTEC Wiki ---> https://wiki.phytec.com/productinfo/phycore-am57x/bsp-yocto-tisdk-am57xx/bsp-yocto-tisdk-am57xx-pd18-2-0-quickstart/bsp-yocto-tisdk-am57xx-pd18-1-0-quickstart" .

I have target to add new meta layer "meta-redhawk-sdr" package to existing meta layers.
So, i have cloned redhawk package from 'geotech' git hub and try to build.

I added new meta layer in 'build/conf/bblayers.conf'
:${BSPDIR}/sources/meta-redhawk-sdr \

And after running command "MACHINE=am57xx-phycore-rdk bitbake arago-core-tisdk-image"
iam getting below error (for command : "bitbake redhawk-gpp-image" geting same error)

Error:
/opt/phytec_bsps/yocto_ti/build$ MACHINE=am57xx-phycore-rdk bitbake arago-core-tisdk-image
Loading cache: 100% |###################################################################################################################################################| ETA: 00:00:00
Loaded 2919 entries from dependency cache.
Parsing recipes: 100% |#################################################################################################################################################| Time: 00:00:00
Parsing of 2320 .bb files complete (2319 cached, 1 parsed). 2919 targets, 453 skipped, 0 masked, 0 errors.
WARNING: No recipes available for:
/opt/phytec_bsps/yocto_ti/sources/meta-arago/meta-arago-distro/recipes-security/optee/optee-os_git.bbappend
/opt/phytec_bsps/yocto_ti/sources/meta-processor-sdk/recipes-core/udev/udev_182.bbappend
/opt/phytec_bsps/yocto_ti/sources/meta-phytec/meta-phytec-ti/recipes-support/cpuset/cpuset_1.5.6.bbappend
WARNING: No bb files matched BBFILE_PATTERN_phytec '^/opt/phytec_bsps/yocto_ti/sources/meta-phytec/common/'
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION = "1.30.0"
BUILD_SYS = "x86_64-linux"
NATIVELSBSTRING = "Ubuntu-14.04"
TARGET_SYS = "arm-linux-gnueabi"
MACHINE = "am57xx-phycore-rdk"
DISTRO = "arago"
DISTRO_VERSION = "2016.10"
TUNE_FEATURES = "arm armv7a vfp thumb neon callconvention-hard"
TARGET_FPU = "hard"
meta-processor-sdk = "HEAD:3678d672c9c47a646897286281d4260ac4ace960"
meta-arago-distro
meta-arago-extras = "HEAD:76381bbc10b93ffc6c014154814872b170b93796"
meta-qt5 = "HEAD:2b1871f0d139dc3caaa779a32a1931409c245a36"
meta-networking
meta-python
meta-ruby
meta-oe = "HEAD:851a064b53dca3b14dd33eaaaca9573b1a36bf0e"
meta-ti = "HEAD:d8aa76970a0ba48762c631dfd79dbed49222373b"
meta-linaro-toolchain = "HEAD:9b616ce6d4293387d254f36800389b2910895420"
meta = "HEAD:28da89a20b70f2bf0c85da6e8af5d94a3b7d76c9"
meta-phytec
meta-phytec-ti = "HEAD:086a659eb42b85ca68d21f4bee8eb51cb9ea3019"
meta-redhawk-sdr = "thud:2e3f30e1af435b995ed47a71837b79ef2fe7144c"

NOTE: Preparing RunQueue
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
ERROR: omniorb-native-4.2.3-r0 do_compile: oe_runmake failed
ERROR: omniorb-native-4.2.3-r0 do_compile: Function failed: do_compile (log file is located at /opt/phytec_bsps/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/x86_64-linux/omniorb-native/4.2.3-r0/temp/log.do_compile.15154)
ERROR: Logfile of failure stored in: /opt/phytec_bsps/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/x86_64-linux/omniorb-native/4.2.3-r0/temp/log.do_compile.15154
Log data follows:
| DEBUG: Executing shell function do_compile
| NOTE: make -j 4
| making export in ./src...
| make[1]: Entering directory /opt/phytec_bsps/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/x86_64-linux/omniorb-native/4.2.3-r0/build/src' | making export in src/tool... | make[2]: Entering directory /opt/phytec_bsps/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/x86_64-linux/omniorb-native/4.2.3-r0/build/src/tool'
| making export in src/tool/omkdepend...
| make[3]: Entering directory /opt/phytec_bsps/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/x86_64-linux/omniorb-native/4.2.3-r0/build/src/tool/omkdepend' | File omkdepend hasn't changed. | make[3]: Leaving directory /opt/phytec_bsps/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/x86_64-linux/omniorb-native/4.2.3-r0/build/src/tool/omkdepend'
| making export in src/tool/omniidl...
| make[3]: Entering directory /opt/phytec_bsps/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/x86_64-linux/omniorb-native/4.2.3-r0/build/src/tool/omniidl' | making export in src/tool/omniidl/cxx... | Traceback (most recent call last): | File "<string>", line 1, in <module> | File "/opt/phytec_bsps/yocto_ti/build/arago-tmp-external-linaro-toolchain/sysroots/x86_64-linux/usr/lib/python2.7/distutils/sysconfig.py", line 22, in <module> | PREFIX = os.path.normpath(sys.prefix).replace( os.getenv("BUILD_SYS"), os.getenv("HOST_SYS") ) | TypeError: expected a string or other character buffer object | Traceback (most recent call last): | File "<string>", line 1, in <module> | File "/opt/phytec_bsps/yocto_ti/build/arago-tmp-external-linaro-toolchain/sysroots/x86_64-linux/usr/lib/python2.7/distutils/sysconfig.py", line 22, in <module> | PREFIX = os.path.normpath(sys.prefix).replace( os.getenv("BUILD_SYS"), os.getenv("HOST_SYS") ) | TypeError: expected a string or other character buffer object | make[4]: Entering directory /opt/phytec_bsps/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/x86_64-linux/omniorb-native/4.2.3-r0/build/src/tool/omniidl/cxx'
| making export in src/tool/omniidl/cxx/cccp...
| make[5]: Entering directory /opt/phytec_bsps/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/x86_64-linux/omniorb-native/4.2.3-r0/build/src/tool/omniidl/cxx/cccp' | File omnicpp hasn't changed. | make[5]: Leaving directory /opt/phytec_bsps/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/x86_64-linux/omniorb-native/4.2.3-r0/build/src/tool/omniidl/cxx/cccp'
| g++ -c -isystem/opt/phytec_bsps/yocto_ti/build/arago-tmp-external-linaro-toolchain/sysroots/x86_64-linux/usr/include -O2 -pipe -Wall -Wno-unused -fexceptions -isystem/opt/phytec_bsps/yocto_ti/build/arago-tmp-external-linaro-toolchain/sysroots/x86_64-linux/usr/include -I -DPYTHON_INCLUDE="<Python.h>" -DPYTHON_THREAD_INC="<pythread.h>" -DIDLMODULE_VERSION=""0x2630"" -fPIC -I. -I../../../../../omniORB-4.2.3/src/tool/omniidl/cxx -I../../../../include -I../../../../../omniORB-4.2.3/include -D__OSVERSION__=2 -D__linux__ -D__x86_64__ -o idlpython.o ../../../../../omniORB-4.2.3/src/tool/omniidl/cxx/idlpython.cc
| ../../../../../omniORB-4.2.3/src/tool/omniidl/cxx/idlpython.cc:31:12: error: #include expects "FILENAME" or
| # include PYTHON_INCLUDE
| ^
| ../../../../../omniORB-4.2.3/src/tool/omniidl/cxx/idlpython.cc:47:6: error: #error "omniidl requires Python 1.5.2 or higher"
| # error "omniidl requires Python 1.5.2 or higher"
| ^
| ../../../../../omniORB-4.2.3/src/tool/omniidl/cxx/idlpython.cc:99:15: error: 'PyObject' does not name a type
| static inline PyObject* PyString_FromChar(unsigned char c)
| ^
| ../../../../../omniORB-4.2.3/src/tool/omniidl/cxx/idlpython.cc:150:3: error: 'PyObject' does not name a type
| PyObject* result() { return result_; }
| ^
| ../../../../../omniORB-4.2.3/src/tool/omniidl/cxx/idlpython.cc:152:10: error: 'PyObject' does not name a type
| static PyObject* scopedNameToList(const ScopedName* sn);
| ^
.....
....
....
| ../../../../../omniORB-4.2.3/src/tool/omniidl/cxx/idlpython.cc:1532:15: error: 'm' was not declared in this scope
| PyObject* m = Py_InitModule((char*)"_omniidl", omniidl_methods);
| ^
| ../../../../../omniORB-4.2.3/src/tool/omniidl/cxx/idlpython.cc:1532:52: error: 'omniidl_methods' was not declared in this scope
| PyObject* m = Py_InitModule((char*)"_omniidl", omniidl_methods);
| ^
| ../../../../../omniORB-4.2.3/src/tool/omniidl/cxx/idlpython.cc:1532:67: error: 'Py_InitModule' was not declared in this scope
| PyObject* m = Py_InitModule((char*)"_omniidl", omniidl_methods);
| ^
| ../../../../../omniORB-4.2.3/src/tool/omniidl/cxx/idlpython.cc:1534:44: error: 'PyString_FromString' was not declared in this scope
| PyString_FromString(IDLMODULE_VERSION));
| ^
| ../../../../../omniORB-4.2.3/src/tool/omniidl/cxx/idlpython.cc:1534:45: error: 'PyObject_SetAttrString' was not declared in this scope
| PyString_FromString(IDLMODULE_VERSION));
| ^
| make[4]: *** [idlpython.o] Error 1
| make[4]: Leaving directory /opt/phytec_bsps/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/x86_64-linux/omniorb-native/4.2.3-r0/build/src/tool/omniidl/cxx' | make[3]: *** [export] Error 1 | make[3]: Leaving directory /opt/phytec_bsps/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/x86_64-linux/omniorb-native/4.2.3-r0/build/src/tool/omniidl'
| make[2]: *** [export] Error 1
| make[2]: Leaving directory /opt/phytec_bsps/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/x86_64-linux/omniorb-native/4.2.3-r0/build/src/tool' | make[1]: *** [export] Error 1 | make[1]: Leaving directory /opt/phytec_bsps/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/x86_64-linux/omniorb-native/4.2.3-r0/build/src'
| make: *** [all] Error 1
| ERROR: oe_runmake failed
| ERROR: Function failed: do_compile (log file is located at /opt/phytec_bsps/yocto_ti/build/arago-tmp-external-linaro-toolchain/work/x86_64-linux/omniorb-native/4.2.3-r0/temp/log.do_compile.15154)
ERROR: Task 7988 (virtual:native:/opt/phytec_bsps/yocto_ti/sources/meta-redhawk-sdr/recipes-deps/omniorb/omniorb_4.2.3.bb, do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 2652 tasks of which 2646 didn't need to be rerun and 1 failed.
Waiting for 0 running tasks to finish:

Summary: 1 task failed:
virtual:native:/opt/phytec_bsps/yocto_ti/sources/meta-redhawk-sdr/recipes-deps/omniorb/omniorb_4.2.3.bb, do_compile
Summary: There were 2 WARNING messages shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.

Is i missed to add any package..or lib path ...?
Please suggest me to overcome this issue and what mistake done from my side...?

regards
shravan

**Comment by btgoodwin** [comment]
This appears to be the same issue you posted at the tail of this person's other issue, where I've replied.  Please see the response there and if once you, like the OP, create a build all using the same version of Yocto and are still having problems, then feel free to create a new issue.

I should point out I'm no longer actively involved with this project and I'm not sure who is.  You may want to reach out to Geon directly for support (through the website) once you've done the above.
