### ISSUE TITLE
Running GPP in an embedded target

### ISSUE THREAD

**Issue by rodrigo455** [Geontech/meta-redhawk-sdr#9]
While running a GPP device, I get the output:

**shell-init: error retrieving current directory: getcwd: cannot access parent directories: Success**
**ps: invalid option -- 'o'**
**BusyBox v1.23.1 (2017-05-19 16:57:08 UTC) multi-call binary.**

**Usage: ps**

it seems that **_ps_** from busybox doesn't have options like _-e_ or _-o_.
I don't know if its an issue worth solving with a patch. I was able to run a SigGen component using GPP-arm.

**Comment by btgoodwin** [comment]
Interesting.  We have a [patch](https://github.com/Geontech/meta-redhawk-sdr/blob/master/recipes-devices/gpp/files/05_GPP_ps_e.patch) to remove the `-o` from the call in the GPP's source code, and on one of the Krogoth -based builds we have here, `ps -e` gives a full process listing.  How recent is this build?

**Comment by rodrigo455** [comment]
this patch removes the -e...
well... I'm going to sync the repos and build a new image. to see if it persists... I hope not.
thanks!

**Comment by rodrigo455** [comment]
in order to not open a new issue... I believe there's no `--inplace` option anymore in [nodeconfig.py](https://github.com/RedhawkSDR/USRP_UHD/blob/5.0.0/nodeconfig.py) just a correction for the recipe: [usrp-uhd_5.0.0.bb](https://github.com/Geontech/meta-redhawk-sdr/blob/krogoth/recipes-devices/usrp-uhd/usrp-uhd_5.0.0.bb).

**Comment by rodrigo455** [comment]
just built a new image for zc702-zynq7... usrp was troublesome with this new version, I think the [blog procedure](www.geontech.com/blog/redhawk-sdr-and-an-ettus-e310/) is not working.

same thing for the ps command:

```
root@zc702-zynq7:~# ps -e
ps: invalid option -- 'e'
BusyBox v1.24.1 (2017-07-17 11:23:21 -03) multi-call binary.

Usage: ps
root@zc702-zynq7:~# ps -o
ps: invalid option -- 'o'
BusyBox v1.24.1 (2017-07-17 11:23:21 -03) multi-call binary.

Usage: ps
```

**Comment by btgoodwin** [comment]
I've pulled the `--inplace` comment into the 5.0 I'm working with in pyro -- thanks again.  As for this `ps` issue, hopefully once my build finishes I'll be able to see a work-around/new patch.  Hopefully be back with news shortly.

**Comment by btgoodwin** [comment]
By the way -- I/we really appreciate all the insight and contributions you've made.  Do you have any interest in being added as a contributor to this repo?

**Comment by rodrigo455** [comment]
Thanks Thomas... please save this offer for later, I think I'm not ready for this. I am new to github, to redhawk, to yocto... still learning... I'm happy to contribute, I'll keep raising issues.

**Comment by btgoodwin** [comment]
Up to you :-)  I'm happy to take pull requests as well.  It all just makes
it easier to pull in community changes.

**Comment by btgoodwin** [comment]
@rodrigo455 I've confirmed that on pyro as well, busybox's implementation of ps has no arguments.  The goal of that line is to get the number of active threads, so I've been fooling around with how to replace `ps -eo nlwp`.  This works for me in busybox:

```
cat /proc/[0-9]*/status | sed -rn 's/(Thread.+)([[:digit:]]+$)/\2/p'
```
The full patch is:

```
--- cpp/states/Limits.cpp	2016-07-26 06:56:43.926880000 -0400
+++ cpp-patched/states/Limits.cpp	2016-07-26 06:58:15.362093504 -0400
@@ -122,7 +122,7 @@
   }
 
   try {
-    std::string line = utils::popen("ps -eo nlwp | tail -n +2 | awk '{ num_threads += $1 } END { print num_threads }' ", true);
+    std::string line = utils::popen("cat /proc/[0-9]*/status | sed -rn 's/(Thread.+)([[:digit:]]+$)/\2/p' | awk '{ num_threads += $1 } END { print num_threads }' ", true);
     if ( line != "ERROR" ) {
       std::vector<std::string> values;
       boost::split(values, line, boost::is_any_of(std::string(" \t")), boost::algorithm::token_compress_on );
```

**Comment by rodrigo455** [comment]
hmmm.
 this command gives me:

```
root@zc702-zynq7:~# cat /proc/[0-9]*/status | sed -rn 's/(Thread.+)([[:digit:]]+$)/\2/p'
1
1
1
1
1
1
1
1
```
...
```
1
1
1
1
1
1
```
running this command in ubuntu I get a similar output, but it is quite different from the other command:
```
$ ps -eo nlwp | tail -n +2 | awk '{ num_threads += $1 } END { print num_threads }' 
640
```
a single line with a bigger number.

thanks so far! I'm going to test this later.

**Comment by rodrigo455** [comment]
hmmmm great!
running both commands in ubuntu I get different values:
```
$ cat /proc/[0-9]*/status | sed -rn 's/(Thread.+)([[:digit:]]+$)/\2/p' | awk '{ num_threads += $1 } END { print num_threads }' 
495
$ ps -eo nlwp | tail -n +2 | awk '{ num_threads += $1 } END { print num_threads }' 
635
```
thanks so far! I'm going to test this path later! I'll tell you the results

**Comment by btgoodwin** [comment]
Interesting the numbers are different. I'm sure it's some nuance of how each procedure counts threads ('active', etc.).

The patch has been pulled into the stack of _Pyro_ commits that I'm still chipping my way through right now.

I just found another bug/glitch in how we build the GPP's first node on startup as well as during the recipe.  Then when node-deployer launches on first start-up, it collects those other two generated nodes and gives you two GPPs instead of just the one.  Rather worse than that, the core framework's implementation of uuid is trying to call the shell which results in "command not found" and invalid instantiation ID in the node configuration for the one generated at startup.  I'm going to setup a patch against the core framework to use the python package and remove one of those node generation scripts in my next commit.

**Comment by btgoodwin** [comment]
The v2.0.6-1 tag on master now addresses these issues (and pyro branch).  I tested it along with several other bugs that were discovered along the way with:

```
export MACHINE=qemuarm64
bitbake redhawk-test-image
runqemu qemuarm64
```

The emulated environment will boot with all available components and softpkgs installed along with omninames, omnievents, domain, and GPP node init.d scripts (starting in that order).  I then went into the python shell and used the sandbox (`from ossie.utils import sb`) to create a waveform with a particular component, and then launched it using the domain reference provided by the `redhawk` package (`from ossie.utils import redhawk`).

Thanks again @rodrigo455 for pointing the above issues out and the others you opened.  A lot of this wasn't touched in a _long_ time, and should have been (I apologize).  This is a lot more solid now.

To anyone reading this afterwards wishing the tag was for krogoth: it might as well be.  There is likely no issue with using the v2.0.6-1 tag with a krogoth build.  If anyone confirms this, please submit an issue or [contact us](http://geontech.com/contact-us).  Thanks!

**Comment by rodrigo455** [comment]
Thanks Thomas!
confirming that it works with krogoth... many enhancements! that's great!
There's no fftwf recipe in the pyro branch of [meta-openembedded](https://github.com/openembedded/meta-openembedded/tree/pyro/meta-oe/recipes-support/fftw).

**Comment by btgoodwin** [comment]
Thanks for the confirmation about krogoth!  

And that's another one I somehow missed. 👎   Hopefully this is the last errant/missed commit. 

I remember just deleting that line from nativesdk.inc early on since the package does `PROVIDES` [fftwf](https://github.com/openembedded/meta-openembedded/blob/pyro/meta-oe/recipes-support/fftw/fftw_3.3.6.bb#L18) which is good enough for the libfft softpkg.

Any chance you're at a place where you can test changing it to `fftw` in nativesdk.inc (or just deleting that line)?  If not, I can stand the the environment back up in a bit.

**Comment by rodrigo455** [comment]
not right now... fftwf appears in:

```
[meta-redhawk-sdr]$ grep -r fftwf
recipes-core/images/native-sdk.inc:    fftwf \
recipes-softpkg/fftlib/rh-fftlib_2.0.0.bb:DEPENDS += "rh-dsp fftwf"
recipes-softpkg/fftlib/rh-fftlib_2.0.0.bb:RDEPENDS_${PN} += "rh-dsp fftwf"
```
Just a new issue:
```
$ nodeBooter -D
ERROR:nodebooter - Unable to launch DomainManager Softpkg: No matching implementation found
```
going to investigate

**Comment by btgoodwin** [comment]
Alright, that's a new one.

I'm starting over from scratch over here to see what else may have gone
wrong.

**Comment by rodrigo455** [comment]
nodebooter gets the processor name using `uname` while the meta-redhawk-sdr uses PACKAGE_ARCH... are they different?

**Comment by btgoodwin** [comment]
I was about to bring this up as the reason for the mismatch (mistmatch of
processor declarations).

And unfortunately yes it sounds like those two values can be different.
I've seen some uname responses on embedded builds come back empty, which is
why I patch a lot of these node config python scripts the devices have so
that it doesn't try to guess and then default to x86.

What machine are you targeting (if you can say)?

And I think I see the issue for pyro for my build.  It started off as a
krogoth build, I modified the manifest for pyro and introduced a typo (just
fixed that).  So when the sync occurred, it didn't throw an error...it just
silently failed.  So all my commits, etc., I thought were against Pyro were
actually against krogoth.

I'm going to pull these last couple tags.  It's Revisionist History
(a.k.a., _bad_), but so far I've had to rename iperf to iperf3, fftwf to
fftw (in that include file and the fftlib softpkg for the latter).  That
has my build rolling forward now so I'll see what else is out there over
night.

To everyone who has tried to use Pyro so far and is also reading this
thread: I apologize and am working this now.

**Comment by rodrigo455** [comment]
targeting zc702.
PACKAGE_ARCH = **cortexa9hf-neon**
uname -m gives me **armv7l**

**Comment by btgoodwin** [comment]
If you print out the rest of the environment (bitbake -e <something> >
env.txt), are there any other variables getting set to armv7l then?  Maybe
there's something common being used (I'm searching right now; it looked
like PACKAGE_ARCH was it, at a glance).

Thomas

**Comment by rodrigo455** [comment]
unfortunately there isn't

**Comment by btgoodwin** [comment]
How would you feel about a top-level variable that can be set by the user
(like SDRROOT, etc.)?

For example, `UNAME_MACHINE ?= "armv7l"` and then that variable would
replace the usage of PACKAGE_ARCH in the few patches.  If someone needs
something other than armv7l, they can set it in their configuration or
export it at the command line.

**Comment by rodrigo455** [comment]
BUILD_ARCH is variable we want

**Comment by btgoodwin** [comment]
That seems to be the architecture of the builder (according to the
comments).  When I do that with `MACHINE` set to qemuarm64, `BUILD_ARCH`
gets set to `x86_64`.

**Comment by rodrigo455** [comment]
seems to be a way out... armv7l is nowhere else.

**Comment by btgoodwin** [comment]
I'm trying to figure out a way to pull it the virtual/kernel build (regex
it off wherever it gets hard-coded to the utsname).  My download of the
kernel is taking a long time today... I may have to come back to this in
the morning.

From a couple responses down on this link:

https://unix.stackexchange.com/questions/136959/where-does-uname-get-its-information-from

We might be able to pull it off the #define for UTS_MACHINE once the kernel
is setup.

**Comment by btgoodwin** [comment]
Yep.  That looks positive.  After the `kernel_configcheck` you end up with
`include/generated/compile.h` being populated with `#define UTS_MACHINE
"some_value"`.  I'll patch this in the morning.

**Comment by btgoodwin** [comment]
For me, this value matches the environment variable:
`TRANSLATED_TARGET_ARCH`.  Does it match for you as well?

**Comment by rodrigo455** [comment]
TRANSLATED_TARGET_ARCH="arm" not armv7l

**Comment by btgoodwin** [comment]
Alright, thank you.  What I've come up with is a little bit of a hack.
I've made a recipe (`uname-machine`) that depends on the kernel.  Its
package pulls the value of `UTS_MACHINE` from
`${STAGING_KERNEL_BUILDDIR}/include/generated/compiled.h` and installs it
as the text of a file: `${OSSIEHOME}/share/uname_machine`.  Other recipes
can then pull it in as needed (which I'm doing right now to replace
PACKAGE_ARCH).  I'll post an update on this thread once I push (but I'll
hold off on tagging until you have a chance to try it for yours too).
